name: Run Tests and CodeCov

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14"]
        requirements-file: [
          dj42_cms311.txt,
          dj50_cms41.txt,
          dj51_cms41.txt,
          dj52_cms41.txt,
          dj60_cms50.txt,
        ]
        os: [
          ubuntu-latest,
        ]
        exclude:
          - python-version: "3.14"
            requirements-file: dj42_cms311.txt
            os: ubuntu-latest
          - python-version: "3.14"
            requirements-file: dj50_cms41.txt
            os: ubuntu-latest
          - python-version: "3.14"
            requirements-file: dj51_cms41.txt
            os: ubuntu-latest
          - python-version: "3.14"
            requirements-file: dj52_cms41.txt
            os: ubuntu-latest
          - python-version: "3.10"
            requirements-file: dj60_cms50.txt
            os: ubuntu-latest
          - python-version: "3.11"
            requirements-file: dj60_cms50.txt
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r tests/requirements/${{ matrix.requirements-file }}
        uv pip install .
    - name: Run coverage
      run: |
        source .venv/bin/activate
        coverage run tests/settings.py

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5.5.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
